group=dev.the456gamer.vanillafork
# versioning loosely based on neoforge? i guess its up to whoever uses this :)
# <mcminor>.<mcpatch>.<build>
version=21.8.1
mcVersion=1.21.8

# Set to true while updating Minecraft version
updatingMinecraft=false

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false
